os:
  - linux
  - osx

branches:
  only:
    - master

env:
  - NODE_VERSION="6.9.1"

script: ./scripts/travis-build.sh

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change
